# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{raiff}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Tadman"]
  s.date = %q{2010-12-06}
  s.description = %q{Reads in AIFF file data and audio contents}
  s.email = %q{github@tadman.ca}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/raiff.rb",
     "lib/raiff/chunk.rb",
     "lib/raiff/chunk/common.rb",
     "lib/raiff/chunk/data.rb",
     "lib/raiff/chunk/form.rb",
     "lib/raiff/chunk/sound_data.rb",
     "lib/raiff/file.rb",
     "raiff.gemspec",
     "sample/example-24bit.aiff",
     "test/helper.rb",
     "test/test_raiff.rb"
  ]
  s.homepage = %q{http://github.com/twg/raiff}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby AIFF Reading Library}
  s.test_files = [
    "test/helper.rb",
     "test/test_raiff.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

